import { AttributeRegistry, TagRegistry } from './registry';
import { TAG, ATTR } from './util';

export const attributes = new AttributeRegistry({
	'ti': ATTR('title'),
	'hd': ATTR('hidden'),
	'tab': ATTR('tabindex'),
	'dr': ATTR('draggable'),
	'coe': ATTR('contenteditable'),
	'sp': ATTR('spellcheck'),
	'dir': ATTR('dir'),
	'ln': ATTR('lang'),
	'h': ATTR('href'),
	't': ATTR('target'),
	'r': ATTR('rel'),
	'dl': ATTR('download'),
	'pg': ATTR('ping'),
	's': ATTR('src'),
	'alt': ATTR('alt'),
	'ty': ATTR('type'),
	'ct': ATTR('crossorigin'),
	'lp': ATTR('loop'),
	'au': ATTR('autoplay'),
	'co': ATTR('controls'),
	'mt': ATTR('muted'),
	'pst': ATTR('poster'),
	'wd': ATTR('width'),
	'hg': ATTR('height'),
	'n': ATTR('name'),
	'v': ATTR('value'),
	'p': ATTR('placeholder'),
	'rq': ATTR('required'),
	'rd': ATTR('readonly'),
	'ds': ATTR('disabled'),
	'ck': ATTR('checked'),
	'ml': ATTR('multiple'),
	'mn': ATTR('min'),
	'mx': ATTR('max'),
	'st': ATTR('step'),
	'ac': ATTR('accept'),
	'fm': ATTR('form'),
	'fa': ATTR('formaction'),
	'fe': ATTR('formenctype'),
	'fmth': ATTR('formmethod'),
	'cs': ATTR('colspan'),
	'rs': ATTR('rowspan'),
	'dfr': ATTR('defer'),
	'asc': ATTR('async'),
	'ch': ATTR('charset'),
	'cnt': ATTR('content'),
	'http': ATTR('http-equiv'),
	'd-': ATTR('data-*'),
	'a-': ATTR('aria-*')
});

export const tags = new TagRegistry({
	'!': TAG('html DOCTYPE="html"', 'html'),
	'h': TAG('head'),
	't': TAG('title'),
	'bb': TAG('body'),
	'd': TAG('div'),
	's': TAG('span'),
	'p': TAG('p'),
	'a': TAG('a'),
	'ul': TAG('ul'),
	'ol': TAG('ol'),
	'li': TAG('li'),
	'br': TAG('br', true),
	'hr': TAG('hr', true),
	'im': TAG('img', true),
	'lk': TAG('link', true),
	'm': TAG('meta', true),
	'sc': TAG('script'),
	'st': TAG('style'),
	'nv': TAG('nav'),
	'hdr': TAG('header'),
	'ftr': TAG('footer'),
	'sn': TAG('section'),
	'ae': TAG('article'),
	'ade': TAG('aside'),
	'mn': TAG('main'),
	'fm': TAG('form'),
	'i': TAG('input', true),
	'ta': TAG('textarea'),
	'b': TAG('button'),
	'sl': TAG('select'),
	'ot': TAG('option'),
	'll': TAG('label'),
	'ft': TAG('fieldset'),
	'ld': TAG('legend'),
	'te': TAG('table'),
	'thd': TAG('thead'),
	'tby': TAG('tbody'),
	'tft': TAG('tfoot'),
	'tr': TAG('tr'),
	'th': TAG('th'),
	'td': TAG('td'),
	'vd': TAG('video'),
	'ad': TAG('audio'),
	'cv': TAG('canvas'),
	'fe': TAG('figure'),
	'fcn': TAG('figcaption'),
	'bq': TAG('blockquote'),
	'q': TAG('q'),
	'cte': TAG('cite'),
	'cd': TAG('code'),
	'pr': TAG('pre'),
	'em': TAG('em'),
	'str': TAG('strong'),
	'sml': TAG('small'),
	'italic': TAG('i'),
	'bdi': TAG('bdi'),
	'bdo': TAG('bdo'),
	'u': TAG('u'),
	'sub': TAG('sub'),
	'sup': TAG('sup'),
	'mrk': TAG('mark'),
	'rby': TAG('ruby'),
	'rt': TAG('rt'),
	'rp': TAG('rp'),
	'wbr': TAG('wbr', true),
	'ifr': TAG('iframe'),
	'obj': TAG('object'),
	'prm': TAG('param', true),
	'ebd': TAG('embed', true),
	'src': TAG('source', true),
	'trk': TAG('track', true),
	'mtr': TAG('meter'),
	'prs': TAG('progress'),
	'dts': TAG('details'),
	'sum': TAG('summary'),
	'tmpl': TAG('template'),
	'slt': TAG('slot'),
	'pic': TAG('picture'),
	'aa': TAG('area', true),
	'map': TAG('map')
});